version: '3.1'
services:
    mysql:
        image: 'mysql:5.7'
        working_dir: /application
        container_name: mysql
        volumes:
            - '.:/application'
        environment:
            - MYSQL_ROOT_PASSWORD=user
            - MYSQL_DATABASE=homework
            - MYSQL_USER=user
            - MYSQL_PASSWORD=root
        ports:
            - '8081:3306'

    php-fpm:
        image: webdevops/php-apache:7.4
        container_name: php-fpm
        working_dir: /application/webroot
        volumes:
        - .:/application
        environment:
        - WEB_DOCUMENT_ROOT=/application/webroot
        - DATABASE_URL=mysql://user:root@mysql:3306/homework
        ports:
        - "8080:80"     

    # webserver:
    #     image: 'nginx:alpine'
    #     working_dir: /application
    #     container_name: 'nginx'
    #     volumes:
    #         - '.:/application'
    #         - './docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
    #     ports:
    #         - '8080:80'

    # php-fpm:
    #     build: docker/php-fpm
    #     working_dir: /application/webroot
    #     container_name: php-fpm
    #     volumes:
    #         - '.:/application/webroot'
    #         - './docker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini'
